- .github/workflows/deploy.dev.yml
- .github/workflows/deploy.prod.yml
- .nais/config.dev.yaml
- .nais/config.prod.yaml
- src/pages/api/proxy.ts
- src/utils/fetch.ts
- Går mot tilbakemeldinger-api i FSS
- Proxyer kall via serversiden
> Tilb api fss

- .github/workflows/deploy.dev.yml
- .github/workflows/deploy.prod.yml
- .npmrc
- Dockerfile
- next-env.d.ts
- package-lock.json
- package.json
- src/components/SamiskSamtaleApp.tsx
- tsconfig.json
jsdom satt til 16.7 (ikke latest 20.0) p.g.a. nav-dekoratoren-moduler
> Bump alle dependencies + npm package oppsett

- .env.development
- .github/workflows/deploy.dev.yml
- .github/workflows/deploy.prod.yml
- .nais/config.dev.yaml
- .nais/config.prod.yaml
- next.config.js
- package-lock.json
- package.json
- src/components/SamiskSamtaleApp.tsx
- src/components/SamiskSamtaleOrderForm.tsx
- src/global.css
- src/localization/LocaleString.tsx
- src/localization/nb.tsx
- src/localization/se.tsx
- src/pages/_app.tsx
- src/pages/_document.tsx
- src/urls.ts
- src/utils/decorator.tsx
Ref. https://github.com/navikt/nav-enonicxp/issues/1572
> Bokmaalsversjon av samisk bestilling

- .env.development
- .github/workflows/deploy.dev.yml
- .github/workflows/deploy.prod.yml
- .nais/config.dev.yaml
- .nais/config.prod.yaml
- package-lock.json
- package.json
- src/global.d.ts
- src/pages/_document.tsx
- src/utils/decorator.tsx
- Oppdatering av accessPolicy
- Tar i bruk nav-dekoratoren-moduler 2.0
- node 18 + generell bumping
Testet lokalt og på dev
> Access policy upgrade

- .github/workflows/deploy.dev.yml
- .nais/config.dev.yaml
- next.config.js
- package-lock.json
- package.json
-   next.js 12->13 + generell bumping
-  ingress i dev -> intern.dev.nav.no
Har testet selv lokalt og i dev
> Dependencies 202305

- package-lock.json
- package.json
Oppdatering av dependencies per 30.05.2023
Har testet i dev
> Dependencies 30052023

- package-lock.json
- package.json
Bumpet alt til siste versjon. Beholder node 18.
> Bump dependencies juni 2023 - Beholder node på v18

- package-lock.json
- package.json
- server/package.json
- server/src/utils/cacheMiddleware.ts
> 2023 uke42 dependencies

- src/components/SamiskSamtaleApp.tsx
- src/components/SamiskSamtaleOrderForm.tsx
- maincontent for å støtte skiplink
- autocomplete på tekstfelter
Har testet selv lokalt og i dev
> UU: maincontent and input

- common/localization/nb.ts
- common/localization/se.ts
- index.html
- package-lock.json
- package.json
- src/components/SamiskSamtaleApp.module.css
- src/components/SamiskSamtaleApp.tsx
- src/components/SamiskSamtaleOrderForm.tsx
- src/main-client.tsx
- Rettet feil i feilmelding for valg av tidsperiode
- Bedre sjekk på telefonnummer
- Statusmeldinger lese opp i skjermleser (UU)
- Bedre html og styling i veilederpanelet (UU)
- Setter maincontent på html-template for å unngå problemer med skiplink ved clientside rendring (UU)
- Bump dependencies (inkl. aksel)
> Input forbedringer

- package-lock.json
- package.json
- src/components/SamiskSamtaleApp.tsx
> instrument client with grafana faro

- .env.development
- .nais/config.yaml
- package-lock.json
- package.json
- server/src/utils/decorator.ts
- Oppgradere moduler pakke
- Ta i bruk decorator-next på dev
> Decorator next env

- .github/workflows/build-and-deploy.yml
- .github/workflows/deploy.dev.ekstern.yml
- .github/workflows/deploy.dev.yml
- .github/workflows/deploy.prod.yml
Fjerner deploy key etter at nais støtter dette under panseret.
Testet i dev
> Fjerne deploy key

- .github/workflows/deploy.dev.ekstern.yml
Deploye til ekstern.dev for testing av nye dekoratøren
> Job for deploying to ekstern.dev

- package-lock.json
- package.json
- server/package.json
> Bump, aksel 6

- common/localization/nb.ts
- src/components/SamiskSamtaleOrderForm.tsx
Tekstjustering norsk (samisk oversettelse kommer)
> Tekstjustering

- package-lock.json
- package.json
- server/package.json
Bump dependencies. Tekstjustering ble tatt i en egen PR (misvisende commit message)
> Dependencies 202404

- package-lock.json
- package.json
- server/src/utils/decorator.ts
Fikser lintingfeil. Kun en teknisk fiks som kun gjelder ved lokal kjøring.
Testes i dev
> Fikser typefeil ved manglene localUrl

- package-lock.json
- package.json
- server/package.json
Bump dependencies inkl nav-dekoratoren-moduler 2.1.6 -> 3.1.0
> Bump dependencies

- LICENSE.md
- README.md
- common/localization/nb.ts
- common/localization/se.ts
> Endret fra NAV til Nav

- index.html
- package-lock.json
- package.json
- server/package.json
- src/components/SamiskSamtaleOrderForm.tsx
- Bump dependencies
- Bytte fra Panel (deprecated) til Box
Har testet selv i dev 
Hvorfor kommer ikke DOCTYPE med når index.html rendres av Vite?
> Bump dependencies inkl. Aksel bytte fra Panel til Box + fix index.html

- index.html
> Tester deploy og rollback

- index.html
Reverserer testendringer etter testrollback
> Reverserer testendringer
